const fs = require('fs');

const navTranslations = {
  "Student Portal": "மாணவர் வலைவாசல்",
  "Parent Portal": "பெற்றோர் வலைவாசல்",
  "Teacher Portal": "ஆசிரியர் வலைவாசல்",
  "Headmaster Portal": "தலைமையாசிரியர் வலைவாசல்",
  "Block Education Officer": "வட்டாரக் கல்வி அலுவலர்",
  "District Education Officer": "மாவட்டக் கல்வி அலுவலர்",
  "Commissioner Portal": "ஆணையர் வலைவாசல்",
  "Minister Dashboard": "அமைச்சர் முகப்பு",
  "Super Admin": "சூப்பர் அட்மின்",
  "Portal Home": "முகப்பு",
  "AI Tutor": "AI ஆசிரியர்",
  "AI Lessons": "AI பாடங்கள்",
  "Digital Library": "டிஜிட்டல் நூலகம்",
  "Personal Guide": "தனிப்பட்ட வழிகாட்டி",
  "Assessments": "மதிப்பீடுகள்",
  "Academic History": "கல்வி வரலாறு",
  "Dashboard": "டாஷ்போர்டு",
  "Academics & Subjects": "கல்வி & பாடங்கள்",
  "Learning Hub": "கற்றல் மையம்",
  "Class Syllabus Board": "வகுப்பு பாடத்திட்ட பலகை",
  "My Subjects": "எனது பாடங்கள்",
  "Homework": "வீட்டுப்பாடம்",
  "Self-Study Plan": "சுய-கற்றல் திட்டம்",
  "Exams & Assessments": "தேர்வுகள் & மதிப்பீடுகள்",
  "Fun Quizzes": "வேடிக்கை வினாடி வினாக்கள்",
  "Competitive Exams": "போட்டித் தேர்வுகள்",
  "Test Preparation": "தேர்வுத் தயாரிப்பு",
  "NEET Preparation": "நீட் தேர்வுத் தயாரிப்பு",
  "Maths Formulas": "கணித சூத்திரங்கள்",
  "Science Draw Mat": "அறிவியல் வரைதல் விரிப்பு",
  "Language Coaching": "மொழி பயிற்சி",
  "3D Preview": "3D முன்னோட்டம்",
  "Science Labs & Centers": "அறிவியல் ஆய்வகங்கள் & மையங்கள்",
  "Virtual Labs": "மெய்நிகர் ஆய்வகங்கள்",
  "Science Lab Support": "அறிவியல் ஆய்வக ஆதரவு",
  "Chemistry Lab": "வேதியியல் ஆய்வகம்",
  "Zoology Centre": "விலங்கியல் மையம்",
  "Computer Education": "கணினி கல்வி",
  "Extracurricular & Wellbeing": "பாடத்திட்டம் அல்லாத & நல்வாழ்வு",
  "Sports & Athletics": "விளையாட்டு & தடகள",
  "Extracurriculars": "பாடத்திட்டம் அல்லாதவை",
  "Celebrations": "கொண்டாட்டங்கள்",
  "Cultural Events": "கலாச்சார நிகழ்வுகள்",
  "My Health Report": "எனது சுகாதார அறிக்கை",
  "Wellness": "நல்வாழ்வு",
  "School & Career": "பள்ளி & தொழில்",
  "Announcements": "அறிவிப்புகள்",
  "My Badges": "எனது பதக்கங்கள்",
  "Story Books": "கதை புத்தகங்கள்",
  "Digital Portfolio": "டிஜிட்டல் போர்ட்ஃபோலியோ",
  "Learning Platform": "கற்றல் தளம்",
  "School Press": "பள்ளி செய்தி இதழ்",
  "Welfare & Benefits": "நலன் & நன்மைகள்",
  "Leave Reports": "விடுப்பு அறிக்கைகள்",
  "Support & Safety": "ஆதரவு & பாதுகாப்பு",
  "Personal Counsellor": "தனிப்பட்ட ஆலோசகர்",
  "Report a Concern": "புகார் அளிக்கவும்",
  "Board Prep": "பொதுத் தேர்வுத் தயாரிப்பு",
  "Mock Tests": "மாதிரித் தேர்வுகள்",
  "Study Boost": "கற்றல் ஊக்கம்",
  "Career Aptitude": "தொழில் திறன்",
  "Scholarships": "உதவித்தொகைகள்",
  "NEET/JEE Prep": "NEET/JEE தயாரிப்பு",
  "College Admissions": "கல்லூரி சேர்க்கை",
  "My Classes": "எனது வகுப்புகள்",
  "Science Labs": "அறிவியல் ஆய்வகங்கள்",
  "Subject Analytics": "பொருள் பகுப்பாய்வு",
  "Academics & Guidance": "கல்வி & வழிகாட்டுதல்",
  "Admin & Tools": "நிர்வாகம் & கருவிகள்",
  "AI Lesson Planner": "AI பாடத் திட்டமிடுபவர்",
  "Question Generator": "கேள்வி உருவாக்கி",
  "AI Evaluation": "AI மதிப்பீடு",
  "Student Management": "மாணவர் நிர்வாகம்",
  "Student Profiles": "மாணவர் விவரங்கள்",
  "Student Status": "மாணவர் நிலை",
  "Homework Manager": "வீட்டுப்பாட மேலாளர்",
  "Scholarship Details": "உதவித்தொகை விவரங்கள்",
  "Student Analytics": "மாணவர் பகுப்பாய்வு",
  "Risk Alerts": "ஆபத்து எச்சரிக்கைகள்",
  "Parent Management": "பெற்றோர் நிர்வாகம்",
  "Resources & Admin": "வளங்கள் & நிர்வாகம்",
  "AI Material Hub": "AI பொருள் மையம்",
  "Add Materials": "பொருட்களைச் சேர்",
  "Daily Attendance": "தினசரி வருகை",
  "Leave Requests": "விடுப்பு கோரிக்கைகள்",
  "Club Events": "கிளப் நிகழ்வுகள்",
  "Interactive Modules": "ஊடாடும் தொகுதிகள்",
  "Child Performance": "குழந்தை செயல்பாடு",
  "Attendance": "வருகை",
  "Homework Status": "வீட்டுப்பாட நிலை",
  "Notifications": "அறிவிப்புகள்",
  "Child Health Report": "குழந்தை சுகாதார அறிக்கை",
  "AI Assistant": "AI உதவியாளர்",
  "Scholarship": "உதவித்தொகை",
  "PTA Meetings": "PTA கூட்டங்கள்",
  "People & Staff": "பணியாளர்கள்",
  "Student Monitoring": "மாணவர் கண்காணிப்பு",
  "Promotions": "பதவி உயர்வுகள்",
  "Staff Management": "பணியாளர் நிர்வாகம்",
  "Temporary Staff": "தற்காலிக பணியாளர்கள்",
  "Parents Details": "பெற்றோர்கள் விவரங்கள்",
  "School Alumni": "பள்ளி முன்னாள் மாணவர்கள்",
  "Academics & Records": "கல்வி & பதிவுகள்",
  "Timetable": "கால அட்டவணை",
  "Exam Schedule": "தேர்வு அட்டவணை",
  "Model Exam Results": "மாதிரி தேர்வு முடிவுகள்",
  "Manage Mock Tests": "மாதிரித் தேர்வுகளை நிர்வகி",
  "School Admin & Govt": "பள்ளி நிர்வாகம் & அரசு",
  "School Resources": "பள்ளி வளங்கள்",
  "Mid-Day Meal": "மதிய உணவு",
  "Govt Schemes Update": "அரசு திட்டங்கள் அப்டேட்",
  "Extra Curricular & Info": "கூடுதல் பாடத்திட்டம் & தகவல்",
  "Public Portal Page": "பொது வலைவாசல் பக்கம்",
  "School Events": "பள்ளி நிகழ்வுகள்",
  "Media Gallery": "மீடியா கேலரி",
  "Rewards & Honors": "வெகுமதிகள் & மரியாதைகள்",
  "School History": "பள்ளி வரலாறு",
  "Clubs & Activities": "கிளப்புகள் & செயல்பாடுகள்",
  "Promotion Approvals": "பதவி உயர்வு ஒப்புதல்கள்",
  "Manage Headmasters": "தலைமையாசிரியர்களை நிர்வகி",
  "School Comparisons": "பள்ளி ஒப்பீடுகள்",
  "Attendance Analytics": "வருகை பகுப்பாய்வு",
  "Exam Analytics": "தேர்வு பகுப்பாய்வு",
  "Infrastructure": "உள்கட்டமைப்பு",
  "Teacher Deployment": "ஆசிரியர் நியமனம்",
  "Dropouts Tracking": "இடைநின்றவர்கள் கண்காணிப்பு",
  "Schemes Update": "திட்டங்கள் அப்டேட்",
  "Grievances": "குறைகள்",
  "Financial Reports": "நிதி அறிக்கைகள்",
  "Circulars": "சுற்றறிக்கைகள்",
  "Connect with School": "பள்ளியுடன் தொடர்பு",
  "Manage BEOs": "BEO களை நிர்வகி",
  "District Overview": "மாவட்ட கண்ணோட்டம்",
  "School Rankings": "பள்ளி தரவரிசை",
  "Dropout Heatmap": "இடைநின்றவர்கள் வரைபடம்",
  "Teacher Analytics": "ஆசிரியர் பகுப்பாய்வு",
  "Scholarship Tracking": "உதவித்தொகை கண்காணிப்பு",
  "Learning Outcomes": "கற்றல் விளைவுகள்",
  "Block Comparisons": "வட்டார ஒப்பீடுகள்",
  "Schemes Tracking": "திட்டங்கள் கண்காணிப்பு",
  "Manage DEOs": "DEO களை நிர்வகி",
  "District Comparisons": "மாவட்ட ஒப்பீடுகள்",
  "Policy Monitoring": "கொள்கை கண்காணிப்பு",
  "Budget Utilization": "பட்ஜெட் பயன்பாடு",
  "School Performance": "பள்ளி செயல்பாடு",
  "Infrastructure Score": "உள்கட்டமைப்பு மதிப்பெண்",
  "State Analytics": "மாநில பகுப்பாய்வு",
  "Schemes Overview": "திட்டங்கள் கண்ணோட்டம்",
  "Grievances Redressal": "குறைகள் தீர்வு",
  "Command Center": "கட்டளை மையம்",
  "Manage Commissioners": "ஆணையர்களை நிர்வகி",
  "Live State View": "நேரடி மாநில பார்வை",
  "KPI Monitoring": "KPI கண்காணிப்பு",
  "AI Predictions": "AI கணிப்புகள்",
  "District Reports": "மாவட்ட அறிக்கைகள்",
  "Policy Intelligence": "கொள்கை நுண்ணறிவு",
  "Budget Overview": "பட்ஜெட் கண்ணோட்டம்",
  "Schemes Progress": "திட்டங்கள் முன்னேற்றம்",
  "Infrastructure Projects": "உள்கட்டமைப்பு திட்டங்கள்",
  "Public Grievances": "பொது மக்கள் குறைகள்",
  "Press & Media": "பத்திரிகை & ஊடகம்",
  "System Dashboard": "கணினி டாஷ்போர்டு",
  "People & Access": "பயனர்கள் & அணுகல்",
  "User Management": "பயனர் மேலாண்மை",
  "Role & Permissions": "பங்கு & அனுமதிகள்",
  "School Management": "பள்ளி மேலாண்மை",
  "Headmaster Management": "தலைமையாசிரியர் மேலாண்மை",
  "Academics & Content": "கல்வி & உள்ளடக்கம்",
  "PDF Syllabus Upload": "PDF பாடத்திட்ட பதிவேற்றம்",
  "Syllabus Management": "பாடத்திட்ட மேலாண்மை",
  "Material Library": "பொருள் நூலகம்",
  "Department Modules": "துறை தொகுதிகள்",
  "System & AI": "கணினி & AI",
  "Feature Toggles": "அம்ச மாற்றங்கள்",
  "AI Integration Setup": "AI ஒருங்கிணைப்பு அமைப்பு",
  "Data Flow Monitor": "தரவு ஓட்டம் கண்காணிப்பு",
  "Governance": "ஆளுமை",
  "Manage Ministers": "அமைச்சர்களை நிர்வகி",
  "Page Management": "பக்க மேலாண்மை",
  "Audit & Config": "தணிக்கை & கட்டமைப்பு",
  "System Logs": "கணினி பதிவுகள்",
  "Portal Settings": "வலைவாசல் அமைப்புகள்"
};

const filePath = 'e:/BalaWork/school/TN-Schools/frontend/src/components/PortalLayout.tsx';
let content = fs.readFileSync(filePath, 'utf8');

const strTranslations = JSON.stringify(navTranslations, null, 6).replace(/}$/, '    }');
const injectStr = `
    nav: ${strTranslations.trim()},
`;
content = content.replace(
  /"தமிழ்":\s*{/g,
  '"தமிழ்": {\n    ' + injectStr.trim() + ','
);

content = content.replace(
  /\{item.label\}/g,
  `{currentLanguage === "தமிழ்" ? ((t as any).nav?.[item.label] || item.label) : item.label}`
);

fs.writeFileSync(filePath, content, 'utf8');
console.log('Done!');
